"""Deterministic, offline LLM/embedding provider used in tests and for demos
without API keys. Outputs are clearly marked as stub-generated so the UI can
flag them, but they exercise the full pipeline (validation, citation
enforcement, persistence)."""
from __future__ import annotations

import hashlib
import json
import math
import time

from app.core.config import get_settings
from app.llm.base import EmbeddingResponse, LLMResponse

_NAME = "local_stub"
_MODEL = "missioniq-stub-1"


class LocalStubLLM:
    name = _NAME

    @property
    def default_model(self) -> str:
        return _MODEL

    def is_available(self) -> bool:
        return True

    async def generate_json(
        self,
        *,
        system: str,
        user: str,
        model: str | None = None,
        temperature: float = 0.1,
        max_tokens: int = 2048,
    ) -> LLMResponse:
        start = time.perf_counter()
        # Best-effort: try to find a "Return JSON matching the following schema"
        # block from the prompt and return an empty-but-valid scaffold the
        # module-level validators will fill with placeholder fields.
        skeleton = _build_skeleton(user)
        payload = {
            "__stub__": True,
            "_notice": (
                "Generated by the MissionIQ local stub provider. "
                "Configure OPENAI_API_KEY or ANTHROPIC_API_KEY for real intelligence output."
            ),
            **skeleton,
        }
        text = json.dumps(payload)
        latency_ms = int((time.perf_counter() - start) * 1000)
        return LLMResponse(
            text=text,
            provider=_NAME,
            model=model or _MODEL,
            input_tokens=len((system + user).split()),
            output_tokens=len(text.split()),
            latency_ms=latency_ms,
        )


def _build_skeleton(user_prompt: str) -> dict:
    """Heuristic placeholder skeleton tailored to the prompt id mentioned in the prompt body.

    For each known module prompt, we surface the actual evidence (document
    name, page, snippet) plus the Customer DNA attributes when present so
    the demo feels grounded even without a real LLM. Citations are emitted
    in the exact ``E{n}`` / ``M{n}`` format the prompts advertise.

    Routing priority matters: more-specific module markers must be checked
    BEFORE less-specific ones, because every prompt body happens to contain
    the literal string "executive_summary" inside its JSON schema block.
    """
    lower = user_prompt.lower()
    evidence_refs = _parse_evidence_refs(user_prompt)
    has_evidence = bool(evidence_refs)
    dna = _parse_customer_dna(user_prompt)
    seller_incomplete = _seller_incomplete(user_prompt)

    # ── Module-specific routes ───────────────────────────────────────────
    # Each downstream module prompt advertises unique schema field names.
    # Order matters only for disambiguation between the DNA producer prompt
    # and a generic "executive_summary" fallback.

    # Briefing modules first — they embed upstream field names as inputs, so we
    # disambiguate on their own unique schema keys before the win-strategy check.
    if "opportunity_snapshot" in lower and "executive_recommendation" in lower:
        return _executive_brief_skeleton(evidence_refs, dna, user_prompt)

    if "attractiveness_score" in lower and "escalations" in lower:
        return _gate_review_skeleton(evidence_refs, dna, user_prompt)

    if "decision_drivers" in lower and "required_next_steps" in lower:
        return _bid_decision_skeleton(evidence_refs, dna, user_prompt)

    if (
        "executive_pursuit_recommendation" in lower
        and "black_hat_assessment" in lower
        and "win_confidence_assessment" in lower
    ):
        return _win_strategy_skeleton(evidence_refs, dna, user_prompt)

    if (
        "win_assessment" in lower
        and "fit_score" in lower
        and "strong_fit_areas" in lower
    ):
        return _capability_match_skeleton(evidence_refs, dna, seller_incomplete)

    if (
        "company_summary" in lower
        and "core_capabilities" in lower
        and "profile_completeness" in lower
    ):
        return _company_dna_skeleton(seller_incomplete)

    if "why_requirement_exists" in lower and "customer_priority" in lower:
        return _compliance_matrix_skeleton(evidence_refs, dna)

    if (
        "evaluation_intelligence" in lower
        and "likely_decision_drivers" in lower
        and "potential_discriminators" in lower
    ):
        return _evaluation_criteria_skeleton(evidence_refs, dna)

    if (
        "capture_risks" in lower
        and "proposal_risks" in lower
        and "delivery_risks" in lower
        and "customer_risks" in lower
    ):
        return _risk_register_skeleton(evidence_refs, dna)

    if (
        "strategic_goals" in lower
        and "stakeholder_concerns" in lower
        and "core_values" in lower
        and "operational_challenges" in lower
    ):
        return _customer_dna_skeleton(evidence_refs)

    # ── Opportunity Summary (legacy fallback) ────────────────────────────
    if (
        "opportunity_summary" in lower
        or "opportunity summary" in lower
        or "executive_summary" in lower
        or "executive summary" in lower
    ):
        if not has_evidence:
            return {
                "executive_summary": (
                    "Insufficient context to produce a confident briefing. "
                    "Upload an RFP, PWS, or Sections L & M to enable analysis."
                ),
                "key_findings": [],
                "supporting_evidence": [],
                "recommended_actions": [
                    "Upload the RFP and PWS for this opportunity.",
                    "Upload Sections L & M (Instructions to Offerors and Evaluation Factors).",
                    "Add any past performance documents or capture notes already gathered.",
                ],
                "mission_need": None,
                "scope_summary": None,
                "key_services": [],
                "deliverables": [],
                "timeline": None,
                "risks": [],
                "pursue_indicators": [],
                "no_pursue_indicators": [],
                "citations": [],
            }

        first_ref = evidence_refs[0]
        return {
            "executive_summary": (
                f"[Stub] Source-grounded briefing derived from {len(evidence_refs)} "
                f"evidence chunk(s) including {first_ref['document_name']} "
                f"(page {first_ref['page'] or '?'}). Real model output requires "
                "OPENAI_API_KEY or ANTHROPIC_API_KEY."
            ),
            "key_findings": [
                f"Evidence {ref['ref']} from {ref['document_name']} "
                f"page {ref['page'] or '?'} discusses: "
                f"{ref['snippet'][:140]}…"
                for ref in evidence_refs[:5]
            ],
            "supporting_evidence": [
                {
                    "evidence_ref": ref["ref"],
                    "finding": f"{ref['document_name']} p.{ref['page'] or '?'}",
                }
                for ref in evidence_refs[:5]
            ],
            "recommended_actions": [
                "Review the cited evidence with the capture lead.",
                "Compare requirements against Compliance Matrix (when available).",
                "Schedule a pursue/no-pursue decision review.",
            ],
            "mission_need": f"[Stub] Synthesized from evidence in {first_ref['document_name']}.",
            "scope_summary": "[Stub] Scope inferred from uploaded documents.",
            "key_services": ["[Stub] Service 1", "[Stub] Service 2"],
            "deliverables": ["[Stub] Deliverable 1"],
            "timeline": "[Stub] Period of performance and milestones.",
            "risks": ["[Stub] Risk 1"],
            "pursue_indicators": ["[Stub] Indicator 1"],
            "no_pursue_indicators": [],
            "citations": [
                {
                    "evidence_ref": ref["ref"],
                    "claim": f"Supports finding sourced from {ref['document_name']}.",
                }
                for ref in evidence_refs[:5]
            ],
        }

    # Assistant-style Q&A skeleton
    if "question" in lower and "evidence" in lower:
        if not has_evidence:
            return {
                "status": "insufficient_context",
                "answer": (
                    "I don't have enough source material to answer this confidently. "
                    "Upload the relevant opportunity documents (RFP, PWS, Sections L & M) "
                    "and ask again."
                ),
                "citations": [],
                "follow_ups": [
                    "What documents do you have available to upload?",
                    "Should we link related SAM.gov notices first?",
                ],
            }
        return {
            "status": "ok",
            "answer": (
                f"[Stub] Based on {len(evidence_refs)} evidence chunk(s), the most "
                f"relevant material is {evidence_refs[0]['document_name']} "
                f"(page {evidence_refs[0]['page'] or '?'}). Configure a real LLM "
                "provider for a substantive analyst response."
            ),
            "citations": [{"evidence_ref": ref["ref"]} for ref in evidence_refs[:5]],
            "follow_ups": [
                "Ask about specific Section L requirements.",
                "Ask about evaluation factors in Section M.",
                "Ask about transition or staffing assumptions.",
            ],
        }

    return {"_unknown_prompt": True, "raw_user_prompt_hash": _hash(user_prompt)}


def _parse_evidence_refs(user_prompt: str) -> list[dict]:
    """Best-effort scrape of the [Ek]/[Mk] evidence block in the prompt.

    Returns up to 5 entries with ``ref``, ``document_name``, ``page``, ``snippet``.
    """
    import re

    refs: list[dict] = []
    pattern = re.compile(
        r"\[([EM]\d+)\]\s*(?:\([^)]*\)\s*)?(?:document=|title=)\"?([^\"\n]*)\"?[^\n]*?(?:page=(\d+|\?))?",
        re.IGNORECASE,
    )
    for m in pattern.finditer(user_prompt):
        ref, doc_name, page = m.group(1), m.group(2).strip(), m.group(3)
        start = m.end()
        end = user_prompt.find("---", start)
        snippet = user_prompt[start:end].strip() if end != -1 else ""
        if snippet.startswith("---"):
            snippet = snippet[3:].strip()
        refs.append(
            {
                "ref": ref,
                "document_name": doc_name or "(unknown source)",
                "page": page if page and page != "?" else None,
                "snippet": snippet[:400],
            }
        )
        if len(refs) >= 8:
            break
    return refs


def _hash(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()[:16]


def _seller_incomplete(user_prompt: str) -> bool:
    """Detect the 'Company Profile incomplete' markers the prompts emit."""
    markers = (
        "SELLER-SIDE DATA INCOMPLETE",
        "Company Profile is empty or nearly empty",
        "Company Profile is incomplete",
    )
    return any(m in user_prompt for m in markers)


def _company_dna_skeleton(seller_incomplete: bool) -> dict:
    if seller_incomplete:
        return {
            "company_summary": "Insufficient seller-side data to synthesize a Company DNA Profile.",
            "core_capabilities": [],
            "past_performance": [],
            "contract_vehicles": [],
            "certifications": [],
            "technology_partners": [],
            "differentiators": [],
            "case_studies": [],
            "key_personnel": [],
            "geographic_footprint": None,
            "security_posture": None,
            "delivery_model": None,
            "pricing_posture": None,
            "executive_summary": (
                "The Company Profile is empty. MissionIQ cannot assess whether "
                "we can credibly win or deliver without seller-side data."
            ),
            "key_findings": [],
            "recommended_actions": [
                "Open the Company Profile page and add core capabilities.",
                "Add past performance examples, certifications, and contract vehicles.",
                "Describe the delivery model, security posture, and key personnel.",
            ],
            "confidence": "insufficient",
            "profile_completeness": "empty",
        }
    return {
        "company_summary": (
            "[Stub] A small-business systems integrator with mission operations, "
            "FedRAMP-aligned cyber, and analytics depth. Configure a real LLM "
            "for a defensible synthesis."
        ),
        "core_capabilities": [
            "[Stub] Mission Operations Center Support (mature)",
            "[Stub] FedRAMP Moderate Engineering (mature)",
            "[Stub] Performance Analytics Dashboards (developing)",
        ],
        "past_performance": [
            "[Stub] DHA mission ops (prime)",
            "[Stub] VA analytics modernization (prime)",
        ],
        "contract_vehicles": ["[Stub] 8(a) Sole Source", "[Stub] GSA MAS"],
        "certifications": ["[Stub] 8(a)", "[Stub] SDVOSB", "[Stub] CMMI-3"],
        "technology_partners": ["[Stub] AWS", "[Stub] Microsoft", "[Stub] Splunk"],
        "differentiators": [
            "[Stub] 24x7 SOC with embedded data engineering",
            "[Stub] FedRAMP-aligned managed services",
        ],
        "case_studies": ["[Stub] Stood up a 24x7 ops center in 45 days for a DoD health system."],
        "key_personnel": ["[Stub] Program Manager (PMP, 15 yrs DHA)", "[Stub] ISSO (CISSP)"],
        "geographic_footprint": "[Stub] National; cleared staff in NCR and San Antonio.",
        "security_posture": "[Stub] FedRAMP Moderate experience; IL5 lineage; facility clearance.",
        "delivery_model": "[Stub] Embedded agile pods with a shared 24x7 SOC backbone.",
        "pricing_posture": "[Stub] Competitive value; lean indirect rates.",
        "executive_summary": (
            "[Stub] Company DNA synthesized from the Company Profile. Mature in "
            "mission ops and cyber; developing in analytics. Credible small-business "
            "prime for DHA-scale operations work."
        ),
        "key_findings": [
            "[Stub] Strongest where mission ops and FedRAMP intersect.",
            "[Stub] Analytics is a developing capability — a likely teaming target.",
        ],
        "recommended_actions": [
            "Add CPARS-backed past performance to strengthen the profile.",
            "Catalog named key personnel and their clearances.",
        ],
        "confidence": "medium",
        "profile_completeness": "partial",
    }


def _win_strategy_skeleton(
    evidence_refs: list[dict], dna: dict | None, user_prompt: str
) -> dict:
    e1 = evidence_refs[0]["ref"] if evidence_refs else "E1"
    e2 = evidence_refs[1]["ref"] if len(evidence_refs) > 1 else e1
    mission = (dna or {}).get("mission") if dna else None
    mission_src = "Customer DNA: mission"

    company_missing = "no seller-side synthesis available" in user_prompt
    cap_missing = "CAPABILITY MATCH: *** MISSING" in user_prompt
    eval_missing = "EVALUATION CRITERIA: *** MISSING" in user_prompt
    risk_missing = "RISK REGISTER: *** MISSING" in user_prompt

    inputs_used = ["Customer DNA", "Opportunity Documents"]
    inputs_missing: list[str] = []
    (inputs_missing if company_missing else inputs_used).append("Company DNA")
    (inputs_missing if cap_missing else inputs_used).append("Capability Match")
    (inputs_missing if eval_missing else inputs_used).append("Evaluation Criteria")
    (inputs_missing if risk_missing else inputs_used).append("Risk Register")

    # Confidence is dampened when key seller-side inputs are missing.
    if company_missing or cap_missing:
        level, score = "low", 38
        recommendation = "pursue_with_conditions"
        rec_text = (
            "[Stub] PURSUE WITH CONDITIONS. The customer need is real and aligns "
            "with our lane, but seller-side synthesis is incomplete — complete "
            "Company DNA and Capability Match before committing B&P."
        )
    else:
        level, score = "medium", 58
        recommendation = "pursue"
        rec_text = (
            "[Stub] PURSUE. Our mature mission-ops and security posture map "
            f"directly to {mission or 'the customer mission'}, the incumbent is "
            "beatable on modernization, and our discriminators are credible. The "
            "gap to close is DHA-specific past performance, addressable via teaming."
        )

    return {
        "executive_pursuit_recommendation": rec_text,
        "pursuit_recommendation": recommendation,
        "strengths": [
            {
                "statement": "Mature 24x7 mission-operations capability aligned to the core requirement.",
                "basis": "evidence",
                "sources": [e1, "Company DNA: core_capabilities"]
                if not company_missing
                else [e1],
            },
            {
                "statement": "Security posture (FedRAMP/IL5) matches the customer's risk priorities.",
                "basis": "inference",
                "sources": [mission_src, "Customer DNA: risk_priorities"],
            },
        ],
        "weaknesses": [
            {
                "statement": "Thin DHA-specific past performance relative to the incumbent.",
                "basis": "inference" if not cap_missing else "assumption",
                "sources": ["Capability Match"] if not cap_missing else [],
            },
            {
                "statement": "Analytics is a developing, not mature, capability.",
                "basis": "evidence" if not company_missing else "assumption",
                "sources": ["Company DNA: core_capabilities"]
                if not company_missing
                else [],
            },
        ],
        "key_discriminators": [
            {
                "statement": "SOC-embedded data engineering — operations and analytics under one roof.",
                "basis": "inference",
                "sources": ["Company DNA: differentiators", mission_src]
                if not company_missing
                else [mission_src],
            },
            {
                "statement": "Demonstrated 45-day stand-up minimizes transition risk the customer fears.",
                "basis": "evidence" if not company_missing else "assumption",
                "sources": ["Company DNA: case_studies", "Customer DNA: risk_priorities"]
                if not company_missing
                else [],
            },
        ],
        "black_hat_assessment": [
            {
                "competitor_move": "Incumbent claims continuity and 'no learning curve.'",
                "impact": "Reframes our modernization edge as transition risk.",
                "our_counter": "Lead with a zero-downtime transition plan and our 45-day stand-up proof point.",
                "basis": "inference",
                "sources": [f"{e2}", "Customer DNA: risk_priorities"],
            },
            {
                "competitor_move": "Large prime out-prices on scale and bench depth.",
                "impact": "Pressures our cost story and perceived capacity.",
                "our_counter": "Position lean indirect rates + named SMEs as lower-risk value, not cheap.",
                "basis": "inference",
                "sources": ["M1"] if any(r["ref"].startswith("M") for r in evidence_refs) else [],
            },
        ],
        "likely_evaluator_concerns": [
            {
                "statement": "Can a small business carry 24x7 mission scale without the incumbent?",
                "basis": "inference",
                "sources": ["Customer DNA: stakeholder_concerns", e1],
            },
        ],
        "win_themes": [
            {
                "statement": "Mission continuity without disruption — modernization at zero operational risk.",
                "basis": "inference",
                "sources": [mission_src, "Customer DNA: risk_priorities"],
            },
            {
                "statement": "Security-first operations aligned to the customer's compliance posture.",
                "basis": "evidence",
                "sources": [e1],
            },
        ],
        "competitive_assessment": {
            "summary": (
                "[Stub] Incumbent is the primary threat on continuity; a large prime "
                "threatens on scale/price. We win by reframing the decision around "
                "modernization-at-low-risk rather than status quo."
            ),
            "competitors": [
                {
                    "name": "Incumbent",
                    "positioning": "Continuity and institutional knowledge.",
                    "threat_level": "high",
                    "our_response": "Attack the status-quo cost of stagnation; prove low-risk transition.",
                    "basis": "inference",
                    "sources": ["Customer DNA: mission", e1],
                },
                {
                    "name": "Large prime",
                    "positioning": "Scale, bench depth, aggressive price.",
                    "threat_level": "medium",
                    "our_response": "Differentiate on agility, named SMEs, and mission focus.",
                    "basis": "assumption",
                    "sources": [],
                },
            ],
        },
        "critical_capture_actions": [
            {
                "action": "Secure a teaming partner with DHA-specific past performance.",
                "rationale": "Closes our most exploitable weakness before the incumbent frames it.",
                "priority": "immediate",
                "owner": "Capture Lead",
            },
            {
                "action": "Schedule customer meetings to validate transition concerns and decision drivers.",
                "rationale": "Converts inferences and assumptions into evidence before bid decision.",
                "priority": "near_term",
                "owner": None,
            },
            {
                "action": "Develop the zero-downtime transition proof package.",
                "rationale": "Neutralizes the incumbent's strongest message.",
                "priority": "pre_rfp",
                "owner": "Solution Architect",
            },
        ],
        "win_confidence_assessment": {
            "level": level,
            "score": score,
            "rationale": (
                "[Stub] Strong capability and mission alignment, offset by past-"
                "performance gap and incumbent continuity advantage."
                + (
                    " Confidence is dampened because key seller-side synthesis "
                    "inputs are missing."
                    if (company_missing or cap_missing)
                    else ""
                )
            ),
            "key_drivers": [
                "Capability/mission alignment (+)",
                "Incumbent continuity advantage (−)",
                "DHA past-performance gap (−)",
            ],
        },
        "inputs_used": inputs_used,
        "inputs_missing": inputs_missing,
        "key_findings": [
            "[Stub] Winnable as a modernization play; not winnable as a price play.",
            "[Stub] Teaming for DHA past performance is the single highest-leverage move.",
        ],
        "citations": [
            {"evidence_ref": ref["ref"], "claim": "Supports win-strategy assessment."}
            for ref in evidence_refs[:4]
        ],
    }


# ── Executive Briefings & Gate Reviews ─────────────────────────────────────


def _briefing_missing(user_prompt: str) -> dict[str, bool]:
    return {
        "company": "no seller-side synthesis available" in user_prompt,
        "win_strategy": "WIN STRATEGY: *** MISSING" in user_prompt,
        "capability_match": "CAPABILITY MATCH: *** MISSING" in user_prompt,
        "evaluation_criteria": "EVALUATION CRITERIA: *** MISSING" in user_prompt,
        "risk_register": "RISK REGISTER: *** MISSING" in user_prompt,
    }


def _memory_present(user_prompt: str) -> bool:
    return (
        "PURSUIT MEMORY" in user_prompt
        and "no prior pursuit history yet" not in user_prompt
    )


def _briefing_inputs(missing: dict[str, bool]) -> tuple[list[str], list[str]]:
    used = ["Customer DNA", "Opportunity Documents"]
    miss: list[str] = []
    label = {
        "company": "Company DNA",
        "win_strategy": "Win Strategy",
        "capability_match": "Capability Match",
        "evaluation_criteria": "Evaluation Intelligence",
        "risk_register": "Risk Intelligence",
    }
    for key, name in label.items():
        (miss if missing[key] else used).append(name)
    return used, miss


def _historical_evidence(present: bool) -> dict:
    if not present:
        return {
            "similar_opportunities": [],
            "historical_win_themes": [],
            "historical_risks": [],
            "historical_discriminators": [],
            "agency_patterns": [],
        }
    return {
        "similar_opportunities": ["[Stub] Prior DHA Mission Ops Recompete"],
        "historical_win_themes": ["[Stub] Mission continuity without disruption"],
        "historical_risks": ["[Stub] Aggressive transition timeline"],
        "historical_discriminators": ["[Stub] Cleared 24x7 SOC bench"],
        "agency_patterns": ["[Stub] Agency consistently weights past performance heavily"],
    }


def _executive_brief_skeleton(
    evidence_refs: list[dict], dna: dict | None, user_prompt: str
) -> dict:
    e1 = evidence_refs[0]["ref"] if evidence_refs else "E1"
    missing = _briefing_missing(user_prompt)
    used, miss = _briefing_inputs(missing)
    seller_weak = missing["company"] or missing["capability_match"]
    mission = (dna or {}).get("mission") if dna else None

    if seller_weak:
        rec, level, score = "pursue_with_conditions", "low", 42
        rationale = (
            "[Stub] The customer need is real and on-mission, but seller-side "
            "synthesis is incomplete. Complete Company DNA and Capability Match "
            "before committing B&P."
        )
    else:
        rec, level, score = "pursue_aggressively", "medium", 62
        rationale = (
            "[Stub] Strong mission alignment, credible discriminators, and a "
            "beatable incumbent justify an aggressive pursuit with disciplined "
            "teaming to close the past-performance gap."
        )

    sp = lambda s, b, src: {"statement": s, "basis": b, "sources": src}  # noqa: E731
    return {
        "headline": (
            f"[Stub] {('Pursue with conditions' if seller_weak else 'Pursue aggressively')}: "
            "on-mission, beatable incumbent, gap is past performance."
        ),
        "opportunity_snapshot": {
            "agency": (dna or {}).get("agency"),
            "program": None,
            "estimated_value": None,
            "contract_vehicle": None,
            "due_date": None,
            "incumbent": None,
            "pursuit_status": "pursue" if not seller_weak else "qualify",
            "win_confidence": score,
        },
        "customer_intelligence": {
            "strategic_priorities": (dna or {}).get("strategic_goals") or [
                "[Stub] Modernize mission operations",
            ],
            "success_metrics": (dna or {}).get("success_metrics") or [
                "[Stub] Operational uptime and mission readiness",
            ],
            "stakeholder_concerns": (dna or {}).get("stakeholder_concerns") or [
                "[Stub] Transition risk; continuity of operations",
            ],
            "mission_drivers": [mission or "[Stub] Mission assurance"],
        },
        "company_position": {
            "strengths": [
                sp(
                    "Mature 24x7 mission-operations capability aligned to the core requirement.",
                    "evidence" if not missing["company"] else "assumption",
                    ["Company DNA: core_capabilities", e1] if not missing["company"] else [],
                ),
            ],
            "gaps": [
                sp(
                    "Thin agency-specific past performance relative to the incumbent.",
                    "inference" if not missing["capability_match"] else "assumption",
                    ["Capability Match"] if not missing["capability_match"] else [],
                ),
            ],
            "proof_points": [
                sp(
                    "Stood up a 24x7 ops center in 45 days for a comparable customer.",
                    "evidence" if not missing["company"] else "assumption",
                    ["Company DNA: case_studies"] if not missing["company"] else [],
                ),
            ],
            "competitive_advantages": [
                sp(
                    "SOC-embedded data engineering — operations and analytics under one roof.",
                    "inference",
                    ["Company DNA: differentiators"] if not missing["company"] else [],
                ),
            ],
        },
        "win_strategy": {
            "recommended_discriminators": [
                sp(
                    "Zero-downtime transition backed by a proven 45-day stand-up.",
                    "inference",
                    ["Win Strategy"] if not missing["win_strategy"] else [],
                ),
            ],
            "key_themes": [
                sp(
                    "Mission continuity without disruption — modernization at low risk.",
                    "inference",
                    ["Customer DNA: risk_priorities"],
                ),
            ],
            "evaluation_priorities": [
                sp(
                    "Lead with past-performance relevance and transition approach.",
                    "inference" if not missing["evaluation_criteria"] else "assumption",
                    ["Evaluation Criteria"] if not missing["evaluation_criteria"] else [],
                ),
            ],
            "critical_actions": [
                {
                    "action": "Secure a teaming partner with agency-specific past performance.",
                    "rationale": "Closes the most exploitable weakness before the incumbent frames it.",
                    "priority": "immediate",
                    "owner": "Capture Lead",
                },
            ],
        },
        "risks": {
            "top_capture_risks": [
                {
                    "title": "Incumbent continuity advantage",
                    "severity": "high",
                    "mitigation": "Reframe decision around modernization-at-low-risk.",
                    "basis": "inference",
                    "sources": [e1],
                },
            ],
            "top_proposal_risks": [
                {
                    "title": "Past-performance relevance gap",
                    "severity": "high",
                    "mitigation": "Team for cited, relevant CPARS.",
                    "basis": "inference" if not missing["capability_match"] else "assumption",
                    "sources": ["Capability Match"] if not missing["capability_match"] else [],
                },
            ],
            "top_delivery_risks": [
                {
                    "title": "Transition timeline compression",
                    "severity": "medium",
                    "mitigation": "Pre-stage cleared staff and runbooks.",
                    "basis": "inference",
                    "sources": ["Customer DNA: risk_priorities"],
                },
            ],
        },
        "executive_recommendation": {
            "recommendation": rec,
            "confidence_level": level,
            "confidence_score": score,
            "rationale": rationale,
            "required_conditions": (
                [
                    "Complete Company DNA and Capability Match.",
                    "Confirm a teaming partner for agency past performance.",
                ]
                if seller_weak
                else ["Confirm a teaming partner for agency past performance."]
            ),
        },
        "historical_evidence": _historical_evidence(_memory_present(user_prompt)),
        "inputs_used": used,
        "inputs_missing": miss,
        "key_findings": [
            "[Stub] Winnable as a modernization play; not as a price play.",
            "[Stub] Teaming for past performance is the highest-leverage move.",
        ],
        "citations": [
            {"evidence_ref": ref["ref"], "claim": "Supports executive brief."}
            for ref in evidence_refs[:4]
        ],
    }


def _gate_review_skeleton(
    evidence_refs: list[dict], dna: dict | None, user_prompt: str
) -> dict:
    e1 = evidence_refs[0]["ref"] if evidence_refs else "E1"
    missing = _briefing_missing(user_prompt)
    used, miss = _briefing_inputs(missing)
    seller_weak = missing["company"] or missing["capability_match"]

    base_basis = "inference"
    align_basis = "evidence" if not missing["company"] else "assumption"
    pwin = 42 if seller_weak else 60
    decision = "pursue_with_conditions" if seller_weak else "pursue"

    def score_block(score, rationale, basis, drivers, sources):
        return {
            "score": score,
            "rationale": rationale,
            "basis": basis,
            "drivers": drivers,
            "sources": sources,
        }

    return {
        "headline": (
            "[Stub] Attractive, winnable opportunity gated on closing the "
            "past-performance gap."
        ),
        "attractiveness_score": score_block(
            72,
            "On-mission, sized to our growth plan, recurring operations scope.",
            base_basis,
            ["Mission alignment", "Recurring revenue"],
            ["Customer DNA: mission", e1],
        ),
        "competitive_position_score": score_block(
            55 if not seller_weak else 45,
            "Beatable incumbent on modernization; large prime threatens on scale.",
            base_basis,
            ["Incumbent beatable", "Prime scale threat"],
            ["Win Strategy"] if not missing["win_strategy"] else [],
        ),
        "capability_alignment_score": score_block(
            68 if not missing["company"] else 50,
            "Mature mission-ops and security align to the core requirement.",
            align_basis,
            ["Mission-ops maturity", "Security posture"],
            ["Company DNA: core_capabilities"] if not missing["company"] else [],
        ),
        "risk_score": score_block(
            58,
            "Higher = more risk. Incumbent continuity and past-performance gap drive it.",
            base_basis,
            ["Incumbent continuity", "Past-performance gap"],
            ["Risk Register"] if not missing["risk_register"] else [],
        ),
        "probability_of_win": {
            "level": "low" if seller_weak else "medium",
            "score": pwin,
            "rationale": (
                "[Stub] Capability and mission alignment offset by incumbent "
                "advantage and a past-performance gap."
                + (" Dampened by missing seller-side inputs." if seller_weak else "")
            ),
        },
        "top_reasons_to_pursue": [
            {
                "statement": "Direct mission alignment with a credible path to differentiate.",
                "basis": base_basis,
                "sources": ["Customer DNA: mission", e1],
            },
            {
                "statement": "Incumbent is beatable on modernization.",
                "basis": "inference" if not missing["win_strategy"] else "assumption",
                "sources": ["Win Strategy"] if not missing["win_strategy"] else [],
            },
        ],
        "top_reasons_not_to_pursue": [
            {
                "statement": "Agency-specific past performance is thin versus the incumbent.",
                "basis": "inference" if not missing["capability_match"] else "assumption",
                "sources": ["Capability Match"] if not missing["capability_match"] else [],
            },
        ],
        "decision_recommendation": decision,
        "decision_summary": (
            "[Stub] Proceed to capture with conditions: secure teaming for past "
            "performance and validate transition concerns with the customer."
        ),
        "required_executive_actions": [
            {
                "action": "Approve B&P for capture phase contingent on teaming.",
                "rationale": "Keeps momentum while de-risking the gap.",
                "priority": "immediate",
                "owner": "Growth VP",
            },
        ],
        "open_questions": [
            "Who is the confirmed teaming partner for agency past performance?",
            "What is the customer's true risk tolerance on transition timing?",
        ],
        "escalations": (
            ["Seller-side synthesis incomplete — complete Company DNA and Capability Match."]
            if seller_weak
            else []
        ),
        "historical_evidence": _historical_evidence(_memory_present(user_prompt)),
        "inputs_used": used,
        "inputs_missing": miss,
        "key_findings": [
            "[Stub] Attractiveness is high; the constraint is competitive proof, not fit.",
        ],
        "citations": [
            {"evidence_ref": ref["ref"], "claim": "Supports gate-review scoring."}
            for ref in evidence_refs[:4]
        ],
    }


def _bid_decision_skeleton(
    evidence_refs: list[dict], dna: dict | None, user_prompt: str
) -> dict:
    e1 = evidence_refs[0]["ref"] if evidence_refs else "E1"
    missing = _briefing_missing(user_prompt)
    used, miss = _briefing_inputs(missing)
    seller_weak = missing["company"] or missing["capability_match"]

    rec = "conditional_bid" if seller_weak else "bid"
    level, score = ("low", 44) if seller_weak else ("medium", 61)

    def factor(name, fscore, rationale, evidence, conf, basis):
        return {
            "name": name,
            "score": fscore,
            "rationale": rationale,
            "evidence": evidence,
            "confidence": conf,
            "basis": basis,
        }

    return {
        "recommendation": rec,
        "executive_summary": (
            "[Stub] "
            + (
                "Conditional bid. The opportunity is strategically aligned and "
                "winnable, but seller-side readiness must be confirmed and a "
                "teaming partner secured before full commitment."
                if seller_weak
                else "Bid. Strong strategic alignment and a beatable incumbent "
                "make this a disciplined, teaming-enabled pursuit worth our B&P."
            )
        ),
        "confidence": {
            "level": level,
            "score": score,
            "rationale": (
                "[Stub] Aggregated across the six decision factors; constrained "
                "by competitive proof and "
                + ("incomplete seller-side inputs." if seller_weak else "past-performance depth.")
            ),
        },
        "factors": [
            factor(
                "Strategic Alignment",
                80,
                "Squarely on-mission and aligned to our growth plan.",
                ["Customer DNA: mission", "Customer DNA: strategic_goals"],
                "high",
                "inference",
            ),
            factor(
                "Revenue Potential",
                70,
                "Sizeable, recurring operations scope.",
                [e1],
                "medium",
                "inference",
            ),
            factor(
                "Relationship Position",
                45,
                "Limited recent customer touchpoints; incumbent is entrenched.",
                [],
                "low",
                "assumption",
            ),
            factor(
                "Competitive Position",
                55 if not missing["win_strategy"] else 45,
                "Beatable incumbent on modernization; prime threatens on scale.",
                ["Win Strategy"] if not missing["win_strategy"] else [],
                "medium" if not missing["win_strategy"] else "low",
                "inference" if not missing["win_strategy"] else "assumption",
            ),
            factor(
                "Delivery Readiness",
                68 if not missing["company"] else 48,
                "Mature mission-ops and security backbone; analytics is developing.",
                ["Company DNA: core_capabilities"] if not missing["company"] else [],
                "medium" if not missing["company"] else "low",
                "evidence" if not missing["company"] else "assumption",
            ),
            factor(
                "Risk Profile",
                52,
                "Higher = lower risk. Past-performance gap and transition timing weigh on it.",
                ["Risk Register"] if not missing["risk_register"] else [],
                "medium",
                "inference" if not missing["risk_register"] else "assumption",
            ),
        ],
        "decision_drivers": [
            "Strategic alignment (strong +)",
            "Competitive proof / past performance (constraint −)",
            "Teaming to close the gap (enabler)",
        ],
        "required_next_steps": [
            {
                "action": "Confirm a teaming partner with agency past performance.",
                "rationale": "Single highest-leverage move to convert conditional to full bid.",
                "priority": "immediate",
                "owner": "Capture Lead",
            },
            {
                "action": "Schedule customer engagements to validate transition concerns.",
                "rationale": "Converts assumptions into evidence before the bid decision.",
                "priority": "near_term",
                "owner": None,
            },
        ],
        "historical_evidence": _historical_evidence(_memory_present(user_prompt)),
        "inputs_used": used,
        "inputs_missing": miss,
        "citations": [
            {"evidence_ref": ref["ref"], "claim": "Supports bid/no-bid decision."}
            for ref in evidence_refs[:4]
        ],
    }


def _capability_match_skeleton(
    evidence_refs: list[dict], dna: dict | None, seller_incomplete: bool
) -> dict:
    e_refs = [r["ref"] for r in evidence_refs[:4]] or ["E1"]
    mission_anchor = (dna or {}).get("mission", "the customer's mission") if dna else "the customer's mission"

    if seller_incomplete:
        return {
            "executive_summary": (
                "[Stub] A fit assessment was produced, but the Company Profile is "
                "incomplete — every seller-side claim below is an ASSUMPTION."
            ),
            "win_assessment": (
                "[Assumption — Company Profile incomplete] Cannot credibly judge "
                "win/deliver confidence without seller-side data. Complete the "
                "Company Profile for a grounded verdict."
            ),
            "fit_score": "moderate",
            "seller_data_complete": False,
            "strong_fit_areas": [],
            "weak_fit_areas": [],
            "missing_capabilities": [
                "[Assumption] Unknown — Company Profile not populated."
            ],
            "required_proof_points": [
                "[Assumption] Cannot identify proof points without company data."
            ],
            "recommended_teaming_partners": [],
            "suggested_discriminators": [],
            "reusable_win_themes": [],
            "capture_questions": [
                "What are our actual capabilities, past performance, and certifications?",
            ],
            "proposal_risks": [
                {
                    "title": "[Assumption] Seller-side data missing",
                    "description": "No Company Profile to assess gaps against.",
                    "severity": "high",
                    "mitigation": "Complete the Company Profile, then re-run Capability Match.",
                }
            ],
            "key_findings": ["[Stub] Seller-side data incomplete."],
            "recommended_actions": [
                "Complete the Company Profile (capabilities, past performance, certifications).",
                "Re-run Capability Match for a grounded win/deliver verdict.",
            ],
            "citations": [],
        }

    return {
        "executive_summary": (
            f"[Stub] Capability match across Customer DNA, requirements, evaluation "
            f"criteria, market intel, and the Company Profile. Grounded in "
            f"{len(evidence_refs)} evidence chunk(s)."
        ),
        "win_assessment": (
            "[Stub] We can credibly win and deliver this. Our mature mission-ops and "
            f"FedRAMP capabilities map directly to {mission_anchor}; the main gap is "
            "DHA-specific past performance, which is closable via teaming."
        ),
        "fit_score": "strong",
        "seller_data_complete": True,
        "strong_fit_areas": [
            {
                "area": "24x7 Mission Operations",
                "rationale": "Mature MOC capability maps to the core 24x7 ops requirement and the customer's continuity-of-operations priority.",
                "evidence_refs": e_refs[:1],
                "confidence": "high",
            },
            {
                "area": "FedRAMP / IL5 Security Posture",
                "rationale": "FedRAMP Moderate engineering aligns with the customer's risk priorities and likely Section M security weighting.",
                "evidence_refs": e_refs[:1],
                "confidence": "high",
            },
        ],
        "weak_fit_areas": [
            {
                "area": "Performance Analytics",
                "rationale": "Analytics is only a developing capability vs a likely evaluated subfactor.",
                "evidence_refs": e_refs[:1],
                "confidence": "medium",
            }
        ],
        "missing_capabilities": [
            "[Stub] DHA-specific past performance at full contract scale",
        ],
        "required_proof_points": [
            "[Stub] CPARS for a comparable 24x7 mission-ops contract",
            "[Stub] Named, cleared Program Manager with DHA tenure",
            "[Stub] Evidence of a successful 60-day transition",
        ],
        "recommended_teaming_partners": [
            {
                "partner_profile": "[Stub] Mid-tier analytics firm with DHA past performance",
                "fills_gap": "Performance analytics depth + DHA relevance",
                "rationale": "Closes the analytics gap and adds DHA-specific CPARS.",
            }
        ],
        "suggested_discriminators": [
            "[Stub] Embedded data engineering inside the SOC",
            "[Stub] 45-day stand-up track record",
            "[Stub] 8(a) status with credible scale",
        ],
        "reusable_win_themes": [
            "[Stub] Mission continuity without disruption during transition",
            "[Stub] Security-first operations aligned to FedRAMP/IL5",
        ],
        "capture_questions": [
            "[Stub] Who is the incumbent PM and what is the customer's satisfaction?",
            "[Stub] Is analytics evaluated as a discriminator or table stakes?",
        ],
        "proposal_risks": [
            {
                "title": "[Stub] Thin DHA past performance",
                "description": "Limited DHA-specific CPARS vs the competitive set.",
                "severity": "high",
                "mitigation": "Team with a DHA-experienced sub; cite adjacent DoD health work.",
            },
            {
                "title": "[Stub] Analytics maturity gap",
                "description": "Analytics capability is developing, not mature.",
                "severity": "medium",
                "mitigation": "Bring an analytics teammate and lead with SOC-embedded data engineering.",
            },
        ],
        "key_findings": [
            "[Stub] Strong fit on mission ops and security; gap on analytics + DHA past performance.",
        ],
        "recommended_actions": [
            "Open teaming discussions to close the analytics + past-performance gaps.",
            "Assemble the required proof points before the bid decision.",
        ],
        "citations": [
            {"evidence_ref": ref["ref"], "claim": "Supports fit assessment."}
            for ref in evidence_refs[:4]
        ],
    }


def _parse_customer_dna(user_prompt: str) -> dict | None:
    """Pull the rendered Customer DNA Profile block out of a downstream prompt.

    Returns None if the block isn't present (e.g. the DNA Module itself, or
    a prompt that doesn't consume DNA).
    """
    import re

    if "CUSTOMER DNA PROFILE" not in user_prompt:
        return None
    dna: dict[str, object] = {}
    block_match = re.search(
        r"CUSTOMER DNA PROFILE\s*\n[─-]+\n(.*?)\n\n",
        user_prompt,
        re.DOTALL,
    )
    if not block_match:
        return None
    block = block_match.group(1)
    for raw_line in block.splitlines():
        line = raw_line.strip()
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key_norm = key.strip().lower().rstrip(":").replace(" ", "_").replace("-", "_")
        value = value.strip()
        if key_norm == "mission":
            dna["mission"] = value
        elif key_norm in {"strategic_goals", "core_values", "success_metrics",
                          "operational_challenges", "technology_priorities",
                          "risk_priorities", "stakeholder_concerns"}:
            dna[key_norm] = [s.strip() for s in value.split(";") if s.strip()]
    return dna or None


# ── Module-specific skeleton builders ──────────────────────────────────────


def _customer_dna_skeleton(evidence_refs: list[dict]) -> dict:
    if not evidence_refs:
        return {
            "mission": "Insufficient context to synthesize a Customer DNA Profile.",
            "strategic_goals": [],
            "core_values": [],
            "success_metrics": [],
            "operational_challenges": [],
            "technology_priorities": [],
            "risk_priorities": [],
            "stakeholder_concerns": [],
            "executive_summary": (
                "MissionIQ requires source material before it will synthesize "
                "a customer portrait. Upload the RFP, the agency's strategic "
                "plan, and any sub-organization charter or mission statement."
            ),
            "key_findings": [],
            "supporting_evidence": [],
            "recommended_actions": [
                "Upload the RFP, PWS, and Sections L & M.",
                "Upload the agency strategic plan (e.g. the 5-year plan, IT roadmap).",
                "Add a sub-organization fact sheet if one is available.",
                "Link relevant SAM.gov notices to enrich market context.",
            ],
            "confidence": "insufficient",
            "citations": [],
        }
    first = evidence_refs[0]
    return {
        "mission": (
            f"[Stub DNA] The customer's mission is inferred from "
            f"{first['document_name']} (page {first['page'] or '?'}). "
            "Configure a real LLM for a defensible synthesis."
        ),
        "strategic_goals": [
            "[Stub] Goal 1: modernize mission operations.",
            "[Stub] Goal 2: strengthen continuity of operations.",
            "[Stub] Goal 3: accelerate FedRAMP-aligned cloud adoption.",
        ],
        "core_values": [
            "[Stub] Mission readiness over speed-to-decision.",
            "[Stub] Auditability and traceability.",
            "[Stub] Workforce stewardship.",
        ],
        "success_metrics": [
            "[Stub] 24x7 uptime of mission systems.",
            "[Stub] Reduction in incident MTTR.",
            "[Stub] Cycle time on continuity-of-operations exercises.",
        ],
        "operational_challenges": [
            "[Stub] Aging mission systems and tech debt.",
            "[Stub] Limited internal cyber engineering capacity.",
            "[Stub] Coordination across multiple sub-components.",
        ],
        "technology_priorities": [
            "[Stub] FedRAMP Moderate / IL5 alignment.",
            "[Stub] Zero-trust architecture.",
            "[Stub] Observability + performance dashboards.",
        ],
        "risk_priorities": [
            "[Stub] Mission disruption during transition.",
            "[Stub] Audit findings (OIG / GAO).",
            "[Stub] Cyber incidents during election or budget cycles.",
        ],
        "stakeholder_concerns": [
            "[Stub] Contracting Officer: schedule certainty.",
            "[Stub] Program Manager: incumbent transition risk.",
            "[Stub] Mission Owner: continuity of operations.",
            "[Stub] CIO: cyber posture and FedRAMP timeline.",
        ],
        "executive_summary": (
            f"[Stub] Synthesized from {len(evidence_refs)} evidence chunk(s) "
            f"including {first['document_name']}. Real provider produces a "
            "defensible portrait grounded in the cited material."
        ),
        "key_findings": [
            f"Evidence {ref['ref']}: {ref['snippet'][:140]}…"
            for ref in evidence_refs[:4]
        ],
        "supporting_evidence": [
            {
                "evidence_ref": ref["ref"],
                "finding": f"{ref['document_name']} p.{ref['page'] or '?'}",
            }
            for ref in evidence_refs[:4]
        ],
        "recommended_actions": [
            "Validate inferred attributes with a customer-facing interview.",
            "Add the agency strategic plan to ground strategic_goals.",
            "Link the most recent OIG/GAO report to harden risk_priorities.",
        ],
        "confidence": "medium",
        "citations": [
            {
                "evidence_ref": ref["ref"],
                "claim": f"Supports DNA inference from {ref['document_name']}.",
            }
            for ref in evidence_refs[:4]
        ],
    }


def _compliance_matrix_skeleton(
    evidence_refs: list[dict], dna: dict | None
) -> dict:
    if not evidence_refs:
        return _empty_briefing(
            "Insufficient context to build a Compliance Matrix.",
            "Upload Sections L and M, the PWS, and the SOW.",
        ) | {"rows": [], "coverage_gaps": ["Section L instructions",
                                            "Section M evaluation factors"]}

    goal_anchor = (dna or {}).get("strategic_goals", [""])
    goal_anchor = goal_anchor[0] if goal_anchor else "the customer's mission"

    rows = []
    for i, ref in enumerate(evidence_refs[:6], start=1):
        priority = ["critical", "high", "high", "medium", "medium", "low"][i - 1]
        rows.append(
            {
                "requirement_id": f"L.{i}",
                "requirement_text": ref["snippet"][:180] or "[Stub requirement text]",
                "source_document": ref["document_name"],
                "source_page": int(ref["page"]) if ref["page"] else None,
                "source_section": None,
                "category": ["Technical", "Management", "Past Performance",
                             "Pricing", "Security", "Transition"][i - 1],
                "response_owner": "Capture Lead",
                "proposed_status": "open",
                "notes": "[Stub] Real model produces capture-team commentary here.",
                "why_requirement_exists": (
                    f"[Stub] The customer needs this because it ladders into "
                    f"their mission outcomes (see DNA: {goal_anchor})."
                ),
                "mission_alignment": (
                    f"[Stub] Aligns with the customer's strategic goal: "
                    f"{goal_anchor}."
                ),
                "customer_priority": priority,
            }
        )
    return {
        "executive_summary": (
            f"[Stub] Compliance Matrix derived from {len(evidence_refs)} "
            "evidence chunk(s), weighted by the Customer DNA Profile. "
            "Real LLM output produces 12–40 substantive rows."
        ),
        "key_findings": [
            "[Stub] Heaviest weighting falls on Technical and Management volumes.",
            "[Stub] Security/transition requirements ladder into the customer's risk priorities.",
        ],
        "supporting_evidence": [
            {
                "evidence_ref": ref["ref"],
                "finding": f"Requirement sourced from {ref['document_name']}.",
            }
            for ref in evidence_refs[:4]
        ],
        "recommended_actions": [
            "Confirm Section M weights with the Capture Lead.",
            "Engage a Security SME on transition-period IA controls.",
            "Pull past performance citations matching the top categories.",
        ],
        "rows": rows,
        "coverage_gaps": [
            "[Stub] CDRL list (verify completeness vs Section J).",
            "[Stub] Section L formatting constraints (page limits per volume).",
        ],
        "citations": [
            {
                "evidence_ref": ref["ref"],
                "claim": f"Source for row sourced from {ref['document_name']}.",
            }
            for ref in evidence_refs[:4]
        ],
    }


def _evaluation_criteria_skeleton(
    evidence_refs: list[dict], dna: dict | None
) -> dict:
    if not evidence_refs:
        return _empty_briefing(
            "Insufficient context to produce Evaluation Criteria intelligence.",
            "Upload Section M, Section L, and any DD-254/IA addenda.",
        ) | {
            "factors": [],
            "evaluation_intelligence": (
                "Cannot produce evaluation intelligence without Section M. "
                "Upload it on the Documents tab and regenerate."
            ),
            "likely_decision_drivers": [],
            "potential_discriminators": [],
            "potential_weaknesses": [],
            "strategic_recommendations": [],
        }

    dna_goal = (dna or {}).get("strategic_goals", [""])[0] if dna else ""
    return {
        "executive_summary": (
            "[Stub] Best-value trade-off with Technical and Past Performance "
            "weighted above Price. Decision board is likely to reward "
            "credible continuity-of-operations and transition discipline."
        ),
        "key_findings": [
            "[Stub] Technical Approach is most important per Section M.",
            "[Stub] Past Performance signals weight more than Price.",
            "[Stub] Transition discipline is a likely tiebreaker.",
        ],
        "supporting_evidence": [
            {
                "evidence_ref": ref["ref"],
                "finding": f"Section M / L evidence in {ref['document_name']}.",
            }
            for ref in evidence_refs[:4]
        ],
        "recommended_actions": [
            "Schedule a color-team review on Technical Volume narrative arc.",
            "Validate past performance citations against agency relevance.",
            "Pressure-test transition plan with delivery leadership.",
        ],
        "factors": [
            {
                "factor": "Technical Approach",
                "subfactor": None,
                "importance": "most_important",
                "required_response_elements": [
                    "24x7 ops approach",
                    "transition-in plan",
                    "information assurance approach",
                ],
                "source_section": "Section M.3",
                "source_page": evidence_refs[0]["page"] and int(evidence_refs[0]["page"]),
            },
            {
                "factor": "Management Approach",
                "subfactor": None,
                "importance": "important",
                "required_response_elements": [
                    "Program Manager qualifications",
                    "staffing plan",
                ],
                "source_section": "Section M.4",
                "source_page": None,
            },
            {
                "factor": "Past Performance",
                "subfactor": None,
                "importance": "important",
                "required_response_elements": ["3 references, similar size/scope"],
                "source_section": "Section M.5",
                "source_page": None,
            },
            {
                "factor": "Price",
                "subfactor": None,
                "importance": "less_important",
                "required_response_elements": ["realism", "reasonableness"],
                "source_section": "Section M.6",
                "source_page": None,
            },
        ],
        "evaluation_intelligence": (
            "[Stub] This is a best-value trade-off, not LPTA. The evaluation "
            "board will reward narrative coherence between technical approach, "
            "transition discipline, and past performance. Price discipline "
            "matters but rarely wins. Tie-breakers are likely to be "
            "transition risk and PM credibility."
            + (f" Aligns with customer DNA: {dna_goal}." if dna_goal else "")
        ),
        "likely_decision_drivers": [
            "[Stub] Credible 24x7 ops approach with named PM.",
            "[Stub] Transition discipline that minimizes mission risk.",
            "[Stub] Past performance directly comparable to DHA scope.",
        ],
        "potential_discriminators": [
            "[Stub] FedRAMP Moderate / IL5 lineage.",
            "[Stub] Embedded analytics / observability practice.",
            "[Stub] 8(a) status with credible scale.",
        ],
        "potential_weaknesses": [
            "[Stub] Thin DHA-specific past performance.",
            "[Stub] PM bench depth (single-deep risk).",
            "[Stub] Surge staffing posture during transition.",
        ],
        "strategic_recommendations": [
            "[Stub] Lead Technical narrative with a transition-risk story.",
            "[Stub] Ghost the incumbent on continuity-of-operations gaps.",
            "[Stub] Close past performance gap with a teaming partner.",
            "[Stub] Surface CIO and Mission Owner concerns in win themes.",
        ],
        "citations": [
            {"evidence_ref": ref["ref"], "claim": "Supports evaluation analysis."}
            for ref in evidence_refs[:4]
        ],
    }


def _risk_register_skeleton(
    evidence_refs: list[dict], dna: dict | None
) -> dict:
    if not evidence_refs:
        return _empty_briefing(
            "Insufficient context to produce a defensible Risk Register.",
            "Upload the RFP, PWS, Section M, and any past-performance documents.",
        ) | {
            "capture_risks": [],
            "proposal_risks": [],
            "delivery_risks": [],
            "customer_risks": [],
            "top_risks": [],
        }

    def _risk(
        title: str,
        description: str,
        mission_impact: str,
        probability: str,
        severity: str,
        mitigation: str,
        owner: str | None,
        refs: list[str],
    ) -> dict:
        return {
            "title": title,
            "description": description,
            "mission_impact": mission_impact,
            "probability": probability,
            "severity": severity,
            "mitigation": mitigation,
            "supporting_evidence": refs,
            "owner": owner,
        }

    e_refs = [r["ref"] for r in evidence_refs[:4]] or ["E1"]
    mission_anchor = (dna or {}).get("mission", "mission outcomes") if dna else "mission outcomes"

    capture_risks = [
        _risk(
            "[Stub] Incumbent relationship advantage",
            "Incumbent has multi-year mission knowledge and a sitting PM with weekly customer touchpoints.",
            f"Incumbency could lock in evaluator preference and slow our access to: {mission_anchor}.",
            "high",
            "high",
            "Schedule a Capture-led discovery sweep; identify two customer champions outside the incumbent's daily orbit.",
            "Capture Lead",
            e_refs[:1],
        ),
        _risk(
            "[Stub] Past performance gap in DHA portfolio",
            "Limited prior DHA-specific past performance vs the typical competitive set.",
            "Weakens Past Performance evaluation factor; raises perceived transition risk.",
            "medium",
            "high",
            "Identify and qualify a sub-prime with deep DHA past performance; secure CPARS letters.",
            "Capture Lead",
            e_refs[:1],
        ),
    ]
    proposal_risks = [
        _risk(
            "[Stub] Page limit on Technical Volume",
            "40-page Technical Volume limit is tight given the breadth of 24x7 ops, transition, and IA scope.",
            "Forces hard prioritization; risk of under-developing the differentiating technical narrative.",
            "high",
            "medium",
            "Lock a one-page-per-factor outline at Pink Team; assign a single Volume Lead with cut authority.",
            "Proposal Manager",
            e_refs[:1],
        ),
    ]
    delivery_risks = [
        _risk(
            "[Stub] 60-day transition window for mission-critical ops",
            "Knowledge transfer from incumbent must complete in 60 days for a 24x7 mission system.",
            "Failed transition disrupts continuity-of-operations and triggers customer reputation risk.",
            "medium",
            "critical",
            "Stand up a transition cell with a named TM, IL5-cleared shadow staff, and a 30/60/90 day playbook.",
            "Delivery Lead",
            e_refs[:2],
        ),
        _risk(
            "[Stub] FedRAMP Moderate / IL5 control coverage",
            "Section L.3.3 references FedRAMP Moderate and DoD IL5 controls; control inheritance posture unclear.",
            "Late discovery of control gaps would delay ATO and slip mission availability.",
            "medium",
            "high",
            "Run an IA gap assessment against NIST 800-53 Moderate during proposal phase; document inheritance.",
            "Security Lead",
            e_refs[:1],
        ),
    ]
    customer_risks = [
        _risk(
            "[Stub] OIG / oversight visibility on transition",
            "DHA transitions of mission-critical systems are recurring OIG/GAO audit topics.",
            "An audit finding during transition would impact customer reputation with HASC/SASC oversight.",
            "low",
            "high",
            "Build an audit-ready transition evidence pack (artifacts, decisions, sign-offs) from week one.",
            "Customer Success",
            e_refs[:1],
        ),
    ]
    return {
        "executive_summary": (
            "[Stub] Highest material risk is the 60-day transition window for a "
            "mission-critical 24x7 system. The capture-side advantage of the "
            "incumbent and the past-performance gap are the next two risks "
            "that should drive immediate capture moves."
        ),
        "key_findings": [
            "[Stub] One critical risk (transition severity).",
            "[Stub] Two high-severity capture risks tied to incumbency and past performance.",
            "[Stub] All risks ladder into the customer's mission and stakeholder concerns.",
        ],
        "supporting_evidence": [
            {
                "evidence_ref": ref["ref"],
                "finding": f"Evidence in {ref['document_name']}.",
            }
            for ref in evidence_refs[:4]
        ],
        "recommended_actions": [
            "Convene a Capture-side risk review this week.",
            "Open a teaming dialogue with a candidate sub-prime to close past performance gap.",
            "Stand up the transition cell in parallel with proposal development.",
        ],
        "capture_risks": capture_risks,
        "proposal_risks": proposal_risks,
        "delivery_risks": delivery_risks,
        "customer_risks": customer_risks,
        "top_risks": [r["title"] for r in delivery_risks + capture_risks[:1]],
        "citations": [
            {"evidence_ref": ref["ref"], "claim": "Supports risk identification."}
            for ref in evidence_refs[:4]
        ],
    }


def _empty_briefing(executive_summary: str, action: str) -> dict:
    return {
        "executive_summary": executive_summary,
        "key_findings": [],
        "supporting_evidence": [],
        "recommended_actions": [
            action,
            "Generate the Customer DNA Profile before re-running this module.",
        ],
        "citations": [],
    }


class LocalStubEmbedder:
    """Deterministic pseudo-embedder. Produces a fixed-dimension unit vector
    from the SHA-256 of the input. Useful for offline tests + demos."""

    name = _NAME

    @property
    def default_model(self) -> str:
        return "missioniq-stub-embed-1"

    @property
    def dimension(self) -> int:
        return get_settings().embedding_dim

    def is_available(self) -> bool:
        return True

    async def embed(
        self, texts: list[str], *, model: str | None = None
    ) -> EmbeddingResponse:
        start = time.perf_counter()
        embeddings: list[list[float]] = []
        dim = self.dimension
        for t in texts:
            digest = hashlib.sha256(t.encode("utf-8")).digest()
            # Expand digest deterministically to dim floats in [-1, 1].
            vec: list[float] = []
            seed = int.from_bytes(digest[:8], "big")
            x = seed or 1
            for _ in range(dim):
                x = (x * 1103515245 + 12345) & 0x7FFFFFFF
                vec.append(((x % 20001) - 10000) / 10000.0)
            norm = math.sqrt(sum(v * v for v in vec)) or 1.0
            embeddings.append([v / norm for v in vec])
        latency_ms = int((time.perf_counter() - start) * 1000)
        return EmbeddingResponse(
            embeddings=embeddings,
            provider=_NAME,
            model=model or self.default_model,
            input_tokens=sum(len(t.split()) for t in texts),
            latency_ms=latency_ms,
        )
