"""Deterministic, offline LLM/embedding provider used in tests and for demos
without API keys. Outputs are clearly marked as stub-generated so the UI can
flag them, but they exercise the full pipeline (validation, citation
enforcement, persistence)."""
from __future__ import annotations

import hashlib
import json
import math
import time

from app.core.config import get_settings
from app.llm.base import EmbeddingResponse, LLMResponse

_NAME = "local_stub"
_MODEL = "missioniq-stub-1"


class LocalStubLLM:
    name = _NAME

    @property
    def default_model(self) -> str:
        return _MODEL

    def is_available(self) -> bool:
        return True

    async def generate_json(
        self,
        *,
        system: str,
        user: str,
        model: str | None = None,
        temperature: float = 0.1,
        max_tokens: int = 2048,
    ) -> LLMResponse:
        start = time.perf_counter()
        # Best-effort: try to find a "Return JSON matching the following schema"
        # block from the prompt and return an empty-but-valid scaffold the
        # module-level validators will fill with placeholder fields.
        skeleton = _build_skeleton(user)
        payload = {
            "__stub__": True,
            "_notice": (
                "Generated by the MissionIQ local stub provider. "
                "Configure OPENAI_API_KEY or ANTHROPIC_API_KEY for real intelligence output."
            ),
            **skeleton,
        }
        text = json.dumps(payload)
        latency_ms = int((time.perf_counter() - start) * 1000)
        return LLMResponse(
            text=text,
            provider=_NAME,
            model=model or _MODEL,
            input_tokens=len((system + user).split()),
            output_tokens=len(text.split()),
            latency_ms=latency_ms,
        )


def _build_skeleton(user_prompt: str) -> dict:
    """Heuristic placeholder skeleton tailored to the prompt id mentioned in the prompt body."""
    lower = user_prompt.lower()
    if "opportunity_summary" in lower or "opportunity summary" in lower:
        return {
            "executive_summary": (
                "[Stub output] Insufficient real-model context. This is a deterministic "
                "placeholder demonstrating the end-to-end pipeline."
            ),
            "mission_need": "[Stub] Mission need extracted from uploaded documents.",
            "scope_summary": "[Stub] Scope summary placeholder.",
            "key_services": ["[Stub] Service 1", "[Stub] Service 2"],
            "deliverables": ["[Stub] Deliverable 1"],
            "timeline": "[Stub] Period of performance and milestones.",
            "risks": ["[Stub] Risk 1"],
            "pursue_indicators": ["[Stub] Indicator 1"],
            "no_pursue_indicators": [],
            "key_findings": ["[Stub] Finding 1"],
            "recommended_actions": ["[Stub] Action 1"],
            "citations": [],
        }
    return {"_unknown_prompt": True, "raw_user_prompt_hash": _hash(user_prompt)}


def _hash(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()[:16]


class LocalStubEmbedder:
    """Deterministic pseudo-embedder. Produces a fixed-dimension unit vector
    from the SHA-256 of the input. Useful for offline tests + demos."""

    name = _NAME

    @property
    def default_model(self) -> str:
        return "missioniq-stub-embed-1"

    @property
    def dimension(self) -> int:
        return get_settings().embedding_dim

    def is_available(self) -> bool:
        return True

    async def embed(
        self, texts: list[str], *, model: str | None = None
    ) -> EmbeddingResponse:
        start = time.perf_counter()
        embeddings: list[list[float]] = []
        dim = self.dimension
        for t in texts:
            digest = hashlib.sha256(t.encode("utf-8")).digest()
            # Expand digest deterministically to dim floats in [-1, 1].
            vec: list[float] = []
            seed = int.from_bytes(digest[:8], "big")
            x = seed or 1
            for _ in range(dim):
                x = (x * 1103515245 + 12345) & 0x7FFFFFFF
                vec.append(((x % 20001) - 10000) / 10000.0)
            norm = math.sqrt(sum(v * v for v in vec)) or 1.0
            embeddings.append([v / norm for v in vec])
        latency_ms = int((time.perf_counter() - start) * 1000)
        return EmbeddingResponse(
            embeddings=embeddings,
            provider=_NAME,
            model=model or self.default_model,
            input_tokens=sum(len(t.split()) for t in texts),
            latency_ms=latency_ms,
        )
