"""Salesforce CRM connector — Phase 1, mock provider.

Deterministic offline provider in the same spirit as the ``local_stub`` LLM:
it exercises the full connector → pursuit → automation pipeline (discovery,
idempotent opportunity upserts, attachment ingestion, provenance stamping)
without a live Salesforce org. Every payload is clearly marked as mock data.

Swapping in a real implementation later means replacing ``discover`` /
``fetch_document`` with Salesforce REST (OAuth) calls — the normalized shapes
and the sync engine stay identical.
"""
from __future__ import annotations

from datetime import UTC, datetime, timedelta
from typing import Any, ClassVar

from app.connectors.base import (
    BaseConnectorProvider,
    ConnectorHealth,
    DiscoveryResult,
    ExternalDocument,
    ExternalOpportunity,
)

_MOCK_NOTE = (
    "[Mock Salesforce data] Generated by the MissionIQ mock Salesforce "
    "provider. Connect a live Salesforce org for real CRM ingestion."
)


def _mock_capture_notes(opp_name: str, agency: str) -> str:
    return (
        f"CAPTURE NOTES — {opp_name}\n"
        f"(Synced from mock Salesforce; treat as connector-ingested source material.)\n\n"
        f"Customer: {agency}. The program office has signaled that continuity of "
        "operations and a low-risk transition are the dominant concerns for this "
        "procurement. The incumbent's performance has been adequate but the "
        "customer wants measurable modernization, better reporting, and a "
        "security posture aligned to current federal mandates.\n\n"
        "Evaluation emphasis (per the account team): past performance relevance, "
        "transition approach, and key personnel. Pricing is expected to be "
        "best-value tradeoff, not LPTA.\n\n"
        "Known stakeholders: the COR (risk-averse, transition-focused), the "
        "program director (modernization advocate), and the contracting officer "
        "(schedule-driven).\n"
    )


_FIXTURES: list[dict[str, Any]] = [
    {
        "external_id": "SF-OPP-006A1",
        "name": "DHA Enterprise Mission Operations Support",
        "agency": "Defense Health Agency",
        "naics_code": "541512",
        "contract_vehicle": "8(a) Sole Source",
        "set_aside": "8(a)",
        "estimated_value_cents": 48_500_000_00,
        "incumbent": "Acme Federal Services LLC",
        "due_in_days": 45,
        "capture_stage": "qualification",
    },
    {
        "external_id": "SF-OPP-006B2",
        "name": "VA Health Data Analytics Modernization",
        "agency": "Department of Veterans Affairs",
        "naics_code": "541511",
        "contract_vehicle": "GSA MAS",
        "set_aside": "SDVOSB",
        "estimated_value_cents": 22_000_000_00,
        "incumbent": None,
        "due_in_days": 70,
        "capture_stage": "identification",
    },
]


class SalesforceProvider(BaseConnectorProvider):
    provider_id: ClassVar[str] = "salesforce"
    label: ClassVar[str] = "Salesforce"
    description: ClassVar[str] = (
        "CRM connector. Discovers opportunities from Salesforce and creates "
        "MissionIQ pursuits automatically, ingesting attached capture notes. "
        "Currently backed by a deterministic mock provider — connect a live "
        "org by configuring the instance URL and credential."
    )
    connector_type: ClassVar[str] = "crm"
    auth_mode: ClassVar[str] = "api_key"
    phase: ClassVar[int] = 1
    provides_opportunities: ClassVar[bool] = True
    provides_documents: ClassVar[bool] = True
    config_fields: ClassVar[list[dict[str, Any]]] = [
        {
            "key": "instance_url",
            "label": "Instance URL",
            "placeholder": "https://yourorg.my.salesforce.com",
            "required": False,
        },
        {
            "key": "stage_filter",
            "label": "Opportunity stage filter",
            "placeholder": "e.g. Qualification,Proposal (blank = all)",
            "required": False,
        },
    ]

    async def test_connection(
        self, *, config: dict[str, Any], secret: str | None
    ) -> ConnectorHealth:
        if not secret:
            return ConnectorHealth(
                ok=False,
                message="No credential set. Add an API token to connect Salesforce.",
            )
        return ConnectorHealth(
            ok=True,
            message="Mock Salesforce org reachable. (Deterministic mock provider.)",
        )

    async def discover(
        self,
        *,
        config: dict[str, Any],
        secret: str | None,
        since: datetime | None = None,
    ) -> DiscoveryResult:
        now = datetime.now(UTC)
        opportunities: list[ExternalOpportunity] = []
        for fx in _FIXTURES:
            attachment = ExternalDocument(
                external_id=f"{fx['external_id']}-NOTES",
                filename=f"{fx['external_id']}_capture_notes.txt",
                mime_type="text/plain",
                doc_type="capture_notes",
                fetch_ref=fx["external_id"],
                opportunity_external_id=fx["external_id"],
            )
            opportunities.append(
                ExternalOpportunity(
                    external_id=fx["external_id"],
                    name=fx["name"],
                    agency=fx["agency"],
                    naics_code=fx["naics_code"],
                    contract_vehicle=fx["contract_vehicle"],
                    set_aside=fx["set_aside"],
                    estimated_value_cents=fx["estimated_value_cents"],
                    incumbent=fx["incumbent"],
                    due_date=now + timedelta(days=fx["due_in_days"]),
                    capture_stage=fx["capture_stage"],
                    notes=_MOCK_NOTE,
                    attachments=[attachment],
                )
            )
        return DiscoveryResult(opportunities=opportunities)

    async def fetch_document(
        self, *, config: dict[str, Any], secret: str | None, ref: ExternalDocument
    ) -> bytes:
        fx = next(
            (f for f in _FIXTURES if f["external_id"] == ref.fetch_ref), _FIXTURES[0]
        )
        return _mock_capture_notes(fx["name"], fx["agency"]).encode("utf-8")
